name: JAVA
# Set the UI name
run-name: Java pipeline
# Controls when the workflow will run
on: [workflow_dispatch]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  java-testing:
    name: Java testing
    if: |
      contains(github.event.head_commit.message, '[release]') != true &&
      contains(github.event.head_commit.message, '[package]') != true
    uses: BananazTechnology/bananaz-pipelines/.github/workflows/JAVA-SOFT.yaml@main
  java-package:
    name: Java publish Maven
    if: |
      contains(github.event.head_commit.message, '[package]') == true &&
      github.ref_name == 'main'
    uses: BananazTechnology/bananaz-pipelines/.github/workflows/JAVA-RELEASE-PACKAGE.yaml@main
  java-release:
    name: Java build Docker
    if: |
      contains(github.event.head_commit.message, '[release]') == true &&
      github.ref_name == 'main'
    uses: BananazTechnology/bananaz-pipelines/.github/workflows/JAVA-RELEASE-APP.yaml@main
