name: RELEASE
# Set the UI name
run-name: Java release Maven package to Github Packages
# Controls when the workflow will run
on: [workflow_dispatch]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow builds the Java app!
  release:
    if: contains(github.event.head_commit.message, '[release]') == true
    # Set github UI name
    name: Java Maven builder
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Can build any Java version
    strategy:
      matrix:
        java: [ '11' ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Code Checkout
      - name: Code Checkout
        uses: actions/checkout@v3
      # Runs as Java
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      # Print env
      - name: Print env
        run: env
      # Print settings xml
      - name: Print settings.xml
        run: cat ~/.m2/settings.xml
      # Runs a set of commands using the runners shell
      - name: Publish package
        # Due to bug in temurin maven, we need to use the mvnw wrapper to deploy
        run: bash mvnw --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password