name: SOFT
# Set the UI name
run-name: Node verify build and run SonarQube
# Controls when the workflow will run
on: [workflow_call]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    if: contains(github.event.head_commit.message, '[release]') != true
    # Set github UI name
    name: Node verify builder
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Can build any Node version
    strategy:
      matrix:
        node: [ '16' ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Code Checkout
      - name: Code Checkout
        uses: actions/checkout@v3
      # Setup Node
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      # Install dependencies
      - name: Install dependencies
        run: npm install
      # Build
      - name: Build
        run: npm run build